### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by jschuur** [PaterSantyago/angular-material-design-light#1]
Could you clarify how this is used? Does it set up custom directives that I can then use instead of attaching classes?

**Comment by PaterSantyago** [comment]
Refer Material Design Lite files as it shown [here](http://www.getmdl.io/started/index.html)
Refer angular-mdl.js
And then just include "angular.mdl" to your application: `angular.module('your-app', ['angular.mdl']);`

It will attach necessary javascript behavior according to attached classes

**Comment by jschuur** [comment]
Thanks, @PaterSantyago. I'd seen the MDL site, although not used it myself yet.

Can you clarify what steps this simplifies? Isn't JS behavior already enabled, by simply including the JS component of MDL and then using appropriate classes?

I would recommend a short readme file with a code sample to help others who might be as uncertain as me on how this fits into their development workflow.

**Comment by PaterSantyago** [comment]
@jschuur when you use MDL, JS-behavior attaches on page load event, but if you modify DOM without page-reload, you must enable it for new elements by yourself. So, my directive do it for you.

**Comment by jschuur** [comment]
Thanks for clarifying!
